### PR TITLE
Comments & Status

### PR DESCRIPTION
**Pull request by xniccum**
Enabling comments & stage movement/approval on student profile
Acceptance Criteria:
* Can add comment to student in both TechPoint & Company sections
* Can view comments on student in both TechPoint & Company sections
* Can edit comments on student in both TechPoint & Company sections 
  only if you are the one who made the comment
* Can delete comments on student in both TechPoint & Company sections
* Can see, move, and approve student current status only in TechPoint view

### CODE REVIEW

**Comment by davisnygren** [comment]
Students do not update on dashboard (because the query is being cached).

As a company user I get this for posting a comment:
image

You can also delete other people's comments from the same organization

**Comment by crowleaj** [comment]
Did the previous commit resolve this issue?

**Comment by Doolan** [comment]
## Issues on Dashboard
```Bash
INFO     2017-02-04 17:07:02,259 module.py:788] default: "GET /student HTTP/1.1" 500 96
INFO     2017-02-04 17:07:02,293 module.py:788] default: "GET /public/modules/dashboard/partials/simpleMSFilter.html HTTP/1.1" 304 -
INFO     2017-02-04 17:07:02,293 module.py:788] default: "GET /public/modules/dashboard/partials/toggleMSFilter.html HTTP/1.1" 304 -
```

#### Is there anything I need to change on my set up to make this branch work?

**Comment by crowleaj** [comment]
- Status working and persistent
- Add seems to be working for both views but can't verify
- Can't test edit and delete due to comment rendering error

**Comment by xniccum** [comment]
ready for review

**Comment by davisnygren** [comment]
looks like everything is working

**Pull request merged**
