### PR TITLE
Reviewer module

### PR DESCRIPTION
**Pull request by davisnygren**
Reviewer login portal and initial admin controls page

Acceptance criteria (after clearing and re-seeding database):

Admin portal:
- can create Reviewer group
Reviewer portal:
- can login
- can view students in own group with grades (if already reviewed)
- can enter grade for student
- grades do not appear when logged in as a different Reviewer User

### CODE REVIEW

**Comment by xniccum** [comment]
can't login as review, get "{"code":"NOT_AUTHENTICATED_TECHPOINT"}"

**Comment by crowleaj** [comment]
Is this issue resolved?

**Comment by xniccum** [comment]
just looked again, don't have issue any more

**Comment by Doolan** [comment]
image

**Comment by Doolan** [comment]
Looks good.

## Approved

**Pull request merged**
