### PR TITLE
Enviroments integration

### PR DESCRIPTION
**Pull request by xniccum**
- CircleCi has finally been setup and established
 - Automatiaclly runs tests
 - if pushed to master, will deploy to staging server
 - if pushed to production, will deploy to production server
- updated tests to account for eventual consistency

### CODE REVIEW

**Comment by crowleaj** [comment]
Looks good at a glance but would like master merged in so I can run upload scripts and test locally.

**Comment by Doolan** [comment]
Pull and merge master into this branch before proceeding with the pull request

**Comment by crowleaj** [comment]
I approve.  Good way to handle the proper pdf bucket, although I don't agree with uploading the json authentication credentials to the repo.

**Comment by davisnygren** [comment]
The PDF doesnt appear to be loading correctly for me

broken

**Comment by davisnygren** [comment]
Looks good!

**Comment by Doolan** [comment]
Pull and merge master into this branch before proceeding with the pull request.

All conflicts should be resolved locally before pushed to master

**Comment by Doolan** [comment]
Approved. 
Still don't know what it does though

**Pull request merged**
