### PR TITLE
Password update fix

### PR DESCRIPTION
**Pull request by crowleaj**
Fixes error by checking if the password parameter is empty before attempting to change the password.
Acceptance Criteria:
- Edit a user in Accounts then try logging in again

### CODE REVIEW

**Comment by davisnygren** [comment]
I got a "Please select a group" message trying to edit an admin password so I was unable to test this with the frontend, but that issue is in the master branch.

**Comment by xniccum** [comment]
notices same

**Comment by xniccum** [comment]
is ok to merge in?

**Comment by crowleaj** [comment]
I ran the git diff command to see the difference between master and this branch: 

git diff 43b9f6d506bd71280d7f4bc2f530678550cf1687 89f924ed4bda433ef72e7535eb0919ad62f70e02 -- *
diff --git a/handlers/services/user_services.go b/handlers/services/user_services.go
index e0d042b..9469d04 100644
--- a/handlers/services/user_services.go
+++ b/handlers/services/user_services.go
@@ -43,19 +43,22 @@ func Login(ctx context.Context, email string, password string) ([]byte, error) {
 func Register(ctx context.Context, organizationKey *datastore.Key, user models.User) (int,error) {
        count, err := datastore.NewQuery("User").Ancestor(organizationKey).Filter("Email =", user.Email).Count(ctx)
        if err != nil {
+               log.Printf("Error querying organizations: bad key: %v\n", organizationKey)
                return http.StatusInternalServerError, err
        } else if count != 0 {
                return http.StatusBadRequest, errors.New("User already exist")
        } else {
                //Hash Password
-               pass, err := bcrypt.GenerateFromPassword([]byte(user.Password),14);
+               pass, err := bcrypt.GenerateFromPassword([]byte(user.Password),14)
                if err != nil {
+                       log.Println("Error hashing user password in registration")
                        return http.StatusInternalServerError, err
                }
                user.Password = string(pass)
 
                key := datastore.NewIncompleteKey(ctx, "User", organizationKey)
                if _, err := datastore.Put(ctx, key, &user); err != nil {
+                       log.Println("Error inserting user into Database")
                        return http.StatusInternalServerError, err
                }
                return http.StatusCreated, nil
@@ -96,11 +99,13 @@ func EditUser(ctx context.Context, userKey *datastore.Key, name string, email st
        }
        user.Name = name
        user.Email = email
-       pass, err := bcrypt.GenerateFromPassword([]byte(user.Password),14);
-       if err != nil {
-               return err
+       if password != "" {
+               pass, err := bcrypt.GenerateFromPassword([]byte(password), 14);
+               if err != nil {
+                       return err
+               }
+               user.Password = string(pass)
        }
-       user.Password = string(pass)
        if _, err := datastore.Put(ctx, userKey, &user); err != nil {
                log.Println(err)
                return err


The branch is ok to get merged upon approval:
- Look at user_services.go Register
- Error logging was added
- EditUser was modified to only change the password when necessary
- Edit the password of a user then try logging in

**Pull request merged**
