### PR TITLE
Reformat phase1

### PR DESCRIPTION
**Pull request by Doolan**
# Restructured the Code base

I choose to go organize by module not position so it would be easier to abstract code in the future.

### CODE REVIEW

**Comment by xniccum** [comment]
everything runs fine, but are the services still all grouped together opposed to put in their related modules like everything else?

**Comment by xniccum** [comment]
*why are the services

**Comment by xniccum** [comment]
nevermind is good

**Comment by crowleaj** [comment]
Looks good

**Comment by davisnygren** [comment]
Tests fine

**Pull request merged**
