### PR TITLE
Process control calls

### PR DESCRIPTION
**Pull request by crowleaj**
- Added a light Student query that only retrieves Name GradYear Grade and Gender

- http://localhost:8080/student/light

- Added a query to get all Students that are at least at a specific status

- POST http://localhost:8080/student/status
- body : {"status": "desired status"} ex. {"status": "Undecided"}

where query is one of: "Rejected (Stage 1)", "Rejected (Stage 2)", "Rejected (Stage 3)",
				"Undecided", "Stage 1 Approved", "Stage 2 Approved", "Stage 3 Approved"

Test by running npm test and postman/curl

### CODE REVIEW

**Comment by Doolan** [comment]
## http://localhost:8080/student/light
### Currently returning: 
```JSON
[
 {
    "gradYear": "2017",
    "grade": 0,
    "gender": "female",
    "name": "Adela Hudson"
  },
  {
    "gradYear": "2017",
    "grade": 0,
    "gender": "female",
    "name": "Aileen Austin"
  }
]
```

### Should Return 
```JavaScript
[
 {
    "key": "5880eca9938200b5d42bcc24",
    "name": "Tara Mendoza",
    "gender": "female",
    "gradYear": 2020,
    "workStatus": "TN Visa",
    "ethnicity": "Hispanic or Latino",
    "score": 3.6
  },
  {
    "key": "5880eca905c29cf36243014f",
    "name": "Tonia Acevedo",
    "gender": "female",
    "gradYear": 2019,
    "workStatus": "EAD",
    "ethnicity": "Hispanic or Latino",
    "score": 5.8
  }
]
```
_found in: https://github.com/Xtern-Matching/Xtern-Matching/blob/71-Process-Control-Unit-FE/core/public/js/temp_globals.js_

**Comment by Doolan** [comment]
### http://localhost:8080/student/status/{query}
Calls for this query are hanging

Also, how do you want me to deal with spaces in URL params? @crowleaj

**Comment by Doolan** [comment]
### Update Command
II will also need a call that accepts an object containing a list of student ids and a level
```Javascript
{
   ids: []//array of student ids,
   level: "Stage 2"
}
```
This call should update the stage for all of the students in the array to new level.
-- UNLESS their assigned level is higher than the one provided, in which case there stage should stay the same

**Comment by crowleaj** [comment]
What in particular was the query parameter in the call that hung?

**Comment by crowleaj** [comment]
Status route changed to POST to take status parameter in body

**Comment by Doolan** [comment]
## http://localhost:8080/student/status/ (POST)
is failing

Route:
http://localhost:8080/student/status

Body: 
```
{
	"status": "Stage 2 Approved"
}
```

Console:
```
INFO     2017-02-04 17:51:04,848 module.py:788] default: "POST /student/status HTTP/1.1" 500 65
```

**Comment by crowleaj** [comment]
I am not getting the error.  Can you try again with the updated code and paste the error message associated or stack trace if it fails?  Otherwise its impossible for me to debug with only the above message, I can only guess what is throwing the error.

**Comment by crowleaj** [comment]
Added and tested Move Students to Status

- http://localhost:8080/student/updatestatus

- body : {
   ids: []//array of student ids,
   level: "Stage 2"
}

**Comment by crowleaj** [comment]
Rename score in your code to grade it is a preexisting field.  Ethnicity was added.  GradYear was changed to an int which may cause unintended concequences.  Id was added.  Database seeding should be updated to reflect changes.

**Comment by Doolan** [comment]
## http://localhost:8080/student/light
**Working**

## http://localhost:8080/student/status
 {"status": "Undecided"}

* The call is hanging and freezing out the server. The server is NOT throwing an error, it isn't returning anything at all...


#### I dumped my db and had it reset

**Comment by Doolan** [comment]
I am going to merge this into my branch because I at least need the first call. Is there some place in /student/status that could be resulting in an infinite while loop or something?
@crowleaj

**Comment by Doolan** [comment]
### Request:
Can I get a GET request called http://localhost:8080/student/reviewer
should return the same as http://localhost:8080/student/light  BUT the grade should be the average grade given to the student by the reviewers
Students that don't have any reviewer grades should not returned

**Pull request merged**
