### PR TITLE
CSVs

### PR DESCRIPTION
**Pull request by crowleaj**
Branch will enable exporting of Users.
Acceptance will be:
- new export route GET /student/export
- export tests passing
- open export.csv in test/manual after running npm test

### CODE REVIEW

**Comment by crowleaj** [comment]
CSV is parsing properly with slices and structs included.  Will most likely need to modify after backend refactor branch is merged due to model changes.

**Comment by crowleaj** [comment]
Up to date with master and ready to be evaluated

**Comment by xniccum** [comment]
its seems a little messy in the structure, I see no halting problems

**Comment by davisnygren** [comment]
Works fine for me.

**Pull request merged**
