### PR TITLE
Pdf upload and serve link

### PR DESCRIPTION
**Pull request by crowleaj**
Ability to upload and serve PDF 
Stores in Google Cloud Storage and creates a media link then updates student record to include resume link.
PDFObject has difficulties loading pdf from another site on Firefox and Chrome, works on edge.
Data gets cached by browser, so sometimes request won't reflect updated url

### CODE REVIEW

**Comment by xniccum** [comment]
breaks at several point within service.js and PDF handler

**Comment by crowleaj** [comment]
os import was removed
http://stackoverflow.com/questions/31102871/how-do-you-run-the-google-app-engine-dev-server-with-client-for-google-cloud-sto
Since the go server does not include cloud storage locally, I was pushing to a dev server and testing.  I will set up the testing to point to dev server bucket

**Comment by crowleaj** [comment]
Ready for reevaluation.  Works by using the prod server's default storage bucket.  The environment variable GOOGLE_APPLICATION_CREDENTIALS needs to be set to the path of a file I will upload on slack.  This is to authenticate the server.  This feature may be evaluated by looking at the contents in the appengine console or by entering the link into the browser which will download the document. I was only able to see the document rendered in the Edge browser, we should look into another pdf handler for rendering.

**Comment by Doolan** [comment]
## This Merge request is denied. 
The supported browsers for this application are **Firefox and Chrome**. Edge testing has zero bearing.

The current pdf viewer has been functioning without a problem for a while now. In addition, all features must be able to work inside of a testing environment. 

Please circle back with Niccum to discuss other storage options and approaches to the problem.

####  _Doolan_ & _Niccum_

**Comment by crowleaj** [comment]
Used Mozilla's Pdf.js document renderer and compatibility was restored.  To test, services.js must use a local address and the above mentioned environment variable must be set.

**Comment by xniccum** [comment]
you have a de-authenticated version of the router set as the main
Aside form that, it seems good; switch this back before merging, if that is done, i approve

**Pull request merged**
