### PR TITLE
Account control

### LINKED ISSUE #48: Account Control
## Goals:
Provide a module to allow Techpoint to add/modify/delete other users.

## Acceptance Criteria

*  The Module should only be accessible via the Techpoint module
*  Users should be able to view accounts broken down by type
*  Users should be able to see company accounts broken down by company
*  Users should be able to delete accounts
*  Users should be able to create accounts
    *  The modal should be empty
*  Users should be able to create accounts
    *  The modal should be populated
*  Admin Users should not show up

### Testing
*  View users by category
*  Switching pages and returning should not cause errors in user category display
*  Change Company in drop down
  *  Displayed users should change
*  Add a user
*  Delete a user
*  Update a user
*  Log in with a new user you create

### Special Considerations
*  _This issue is unrelated to consistency issues and effects of weak/strong consistency should be ignored_

### Full Stack
This Branch is a full stack branch. 
@doolan is responsible for the front end.
@crowleaj is responsible for the back end.

### PR DESCRIPTION
**Pull request by Doolan**
# Resolves #48 

Please refer to the testing and acceptance criteria in the corresponding issue (#48)

### CODE REVIEW

**Comment by Doolan** [comment]
capture

**Comment by davisnygren** [comment]
All of the GetUsers requests are responding with null for me

**Comment by xniccum** [comment]
same issue

**Comment by Doolan** [comment]
Closed until conflicts are resolved

**Comment by Doolan** [comment]
Conflicts have been resolved.

**Pull request merged**
